// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nbsmelcznsxrsmjslfff.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ic21lbGN6bnN4cnNtanNsZmZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2MDE4MzYsImV4cCI6MjA2MTE3NzgzNn0.06fv-iGoGo-c-dmoDCGN6sOK4O9ahY2aE-7rzlsobeo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);